### PR TITLE
File reader

### PR DESCRIPTION
**Pull request by mccalluc**
@Muraszko ?
- Would we like to host this on GH Pages, or will folks just have a local copy?
- What should the initial state be... folded or unfolded? (maybe just the first one or two levels...)
- Is there other information we should present along the way?
- What happens when you got to a leaf? Should it link to anything? Show the FITS?
- How robust does it need to be? Right now, it chokes if the root element is not included in the list.

screen shot 2016-06-08 at 12 40 50 pm

### CODE REVIEW

**Comment by mccalluc** [comment]
Talked with Leah, and two things came of that:
- Want to be able to search by substring of path.
- Want a summary of the member files at the folder level.

**Comment by mccalluc** [comment]
Almost have implemented Leah's requests: need to limit it to only some filetypes.

screen shot 2016-06-09 at 2 54 47 pm

**Comment by Muraszko-wgbh** [comment]
@mccalluc 
_Would we like to host this on GH Pages, or will folks just have a local copy?_
Hosted on Github as part of preservation-workflow would be useful to us in the MLA.  Could we also copy it and send it off to folks wanting to browse their file-list.txt file?

_What should the initial state be... folded or unfolded? (maybe just the first one or two levels...)_
Unfolded first two levels is good.  The first level will usually be `/Volumes/` anyway.

_Is there other information we should present along the way?_
Can you do something like show a folder/file count when hovering over a directory?

_What happens when you got to a leaf? Should it link to anything? Show the FITS?_
Based on file path could we point to DAM records hosted in Filemaker?

_How robust does it need to be? Right now, it chokes if the root element is not included in the list._
Doesn't need to be too robust, just a useful visualizer for people used to navigating  folder to folder.

**Comment by mccalluc** [comment]
> _What happens when you got to a leaf? Should it link to anything? Show the FITS?_
> Based on file path could we point to DAM records hosted in Filemaker?

@Muraszko : could you give me an example of the URL you'd like? More information must be necessary... just a file path wouldn't be unique across all of DAM.

**Comment by Muraszko-wgbh** [comment]
@mccalluc That might need some more work than just a URL.  It would probably have to open the DAM Filemaker host and run a search using the file path, which is pretty unique.
We can forget that feature for now though.

**Pull request merged**
